/*
 * Copyright 2026 Pockly contributors
 * SPDX-License-Identifier: Apache-2.0
 */

import test from "node:test";
import assert from "node:assert/strict";

import {
  parseUserMessage,
  attachmentSummary,
  stripInternalContent,
  isCompactSummaryText,
  isDiffTool,
  extractEditPairs,
  lineDiff,
  extractQuestions,
  extractTodos,
  isTodoTool,
  latestSessionUsage,
  contextWindowForAgent,
  tokenUsageTier,
  summarizePendingPermissions,
  parseReaderPreferences,
  DEFAULT_READER_PREFERENCES,
  hasMathSyntax,
  nestSidechainTurns,
  visibleConversationTurns,
  canControlSession,
  isAgentResponseTurnAfter,
  isVisibleAgentProgressTurn,
  isRenderableConversationTurn,
  reconcileHydratedTurns,
  appendStreamingTurn,
  liveMessageStableSeqKey,
  modelOptionLabel,
  modelPillLabel,
  normalizeModelOptions,
  deriveSessionTitle,
  normalizeUserMessageKey,
  resampleMono,
  shouldRestoreFailedSendOnControlError,
} from "./App";
import type { SessionListItem, SessionTurn } from "./api";

test("parseUserMessage classifies a bare prompt as plain", () => {
  const result = parseUserMessage("how do I open the workspace?");
  assert.equal(result.kind, "plain");
  if (result.kind === "plain") {
    assert.equal(result.text, "how do I open the workspace?");
  }
});

test("model pill labels aliases without reverse-selecting resolved targets", () => {
  const options = normalizeModelOptions(
    [
      { value: "sonnet", label: "sonnet", resolved_model: "anthropic-compatible-fast" },
      { value: "opus", label: "opus", resolved_model: "anthropic-compatible-pro" },
      { value: "haiku", label: "haiku", resolved_model: "anthropic-compatible-fast" },
      { value: "anthropic-compatible-fast", label: "anthropic-compatible-fast", resolved_model: "anthropic-compatible-fast" },
    ],
    [],
  );

  assert.equal(modelOptionLabel(options[0]), "sonnet -> anthropic-compatible-fast");
  assert.equal(modelPillLabel("opus", "anthropic-compatible-pro", options), "opus -> anthropic-compatible-pro");
  assert.equal(modelPillLabel("anthropic-compatible-fast", "anthropic-compatible-fast", options), "anthropic-compatible-fast");
  assert.deepEqual(
    options.filter((option) => option.value === "anthropic-compatible-fast").map((option) => option.value),
    ["anthropic-compatible-fast"],
  );
});

test("resampleMono downsamples voice audio to a predictable smaller PCM buffer", () => {
  const source = new Float32Array(48_000);
  for (let index = 0; index < source.length; index += 1) {
    source[index] = index / source.length;
  }

  const downsampled = resampleMono(source, 48_000, 16_000);

  assert.equal(downsampled.length, 16_000);
  assert.equal(downsampled[0], 0);
  assert.ok(downsampled[downsampled.length - 1] > 0.99);
});

test("send failure restoration treats inject_started as not durable", () => {
  assert.equal(shouldRestoreFailedSendOnControlError("idle", false), true);
  assert.equal(shouldRestoreFailedSendOnControlError("started", false), true);
  assert.equal(shouldRestoreFailedSendOnControlError("failed", true), true);
  assert.equal(shouldRestoreFailedSendOnControlError("cancelled", true), true);
  assert.equal(shouldRestoreFailedSendOnControlError("started", true), false);
  assert.equal(shouldRestoreFailedSendOnControlError("streaming", true), false);
  assert.equal(shouldRestoreFailedSendOnControlError("reply_visible", true), false);
});

test("visible agent progress includes tools and permissions, but not thinking", () => {
  assert.equal(isVisibleAgentProgressTurn(turn(1, "user_message", { text: "prompt" })), false);
  assert.equal(isVisibleAgentProgressTurn(turn(2, "thinking", { text: "working" })), false);
  assert.equal(isVisibleAgentProgressTurn(turn(3, "assistant_text", { text: "" })), false);
  assert.equal(isVisibleAgentProgressTurn(turn(4, "assistant_text", { text: "done" })), true);
  assert.equal(isVisibleAgentProgressTurn(turn(5, "tool_call", { tool: "Bash" })), true);
  assert.equal(isVisibleAgentProgressTurn(turn(6, "tool_result", { result: "ok" })), true);
  assert.equal(isVisibleAgentProgressTurn(turn(7, "attachment", { attachment_type: "permission_request" })), true);
});

test("deriveSessionTitle does not leak the local-command-caveat envelope", () => {
  const caveat =
    "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages as if they were direct messages from the user.</local-command-caveat>";
  // Standalone caveat → no usable prose for a title.
  assert.equal(deriveSessionTitle(caveat), "");
  // Caveat followed by a real prompt → only the prompt survives.
  assert.equal(deriveSessionTitle(caveat + "fix the login bug"), "fix the login bug");
});

test("stripInternalContent removes the local-command-caveat envelope", () => {
  const caveat =
    "<local-command-caveat>Caveat: messages below were generated while running local commands.</local-command-caveat>";
  assert.equal(stripInternalContent(caveat), "");
  assert.equal(stripInternalContent(caveat + "real prose"), "real prose");
});

test("parseUserMessage does not surface a standalone caveat as a bubble", () => {
  const caveat =
    "<local-command-caveat>Caveat: messages below were generated while running local commands.</local-command-caveat>";
  const result = parseUserMessage(caveat);
  assert.equal(result.kind, "plain");
  if (result.kind === "plain") {
    assert.equal(result.text, "");
  }
});

// Regression: a background-task completion event (injected as a user-role
// message by the harness) was rendering as a "you" chat bubble. It must be
// stripped like the other internal envelopes.
test("parseUserMessage does not surface a task-notification as a bubble", () => {
  const notif =
    "<task-notification>\n<task-id>bsbn6vsrm</task-id>\n<status>completed</status>\n<summary>Background command \"npm run e2e\" completed (exit code 0)</summary>\n</task-notification>";
  const result = parseUserMessage(notif);
  assert.equal(result.kind, "plain");
  if (result.kind === "plain") {
    assert.equal(result.text, "");
  }
  // Mixed with real prose → only the prose survives.
  const mixed = parseUserMessage(notif + "\nnow run the tests");
  assert.equal(mixed.kind, "plain");
  if (mixed.kind === "plain") {
    assert.equal(mixed.text, "now run the tests");
  }
});

test("normalizeUserMessageKey folds full/half-width punctuation + whitespace", () => {
  // Chinese IME full-width ？ vs ASCII ? must hash the same.
  assert.equal(
    normalizeUserMessageKey("你现在effort是什么档位？"),
    normalizeUserMessageKey("你现在effort是什么档位?"),
  );
  assert.equal(normalizeUserMessageKey("  hi   there \n"), "hi there");
});

test("reconcileHydratedTurns dedups optimistic vs confirmed despite ？/? mismatch", () => {
  const mk = (seq: number, text: string): SessionTurn => ({
    session_id: "s1",
    device_id: "d1",
    seq,
    agent: "claude-code",
    kind: "user_message",
    timestamp: "2026-01-01T00:00:00Z",
    payload: { text },
  } as SessionTurn);
  // Optimistic bubble (what the user typed, half-width ?) at synthetic seq;
  // confirmed turn from the agent (full-width ？) at a real seq. Must collapse
  // to ONE bubble — this is the "sent one message, showed two" report.
  const optimistic = mk(900_000_001, "你现在effort是什么档位?");
  const confirmed = mk(17, "你现在effort是什么档位？");
  const out = reconcileHydratedTurns([optimistic], [confirmed]).filter((t) => t.kind === "user_message");
  assert.equal(out.length, 1, `expected 1 user bubble, got ${out.length}`);
  assert.equal(out[0].seq, 17); // the confirmed copy survives, not the ghost
});

test("reconcileHydratedTurns keeps two genuinely distinct user messages", () => {
  const mk = (seq: number, text: string): SessionTurn => ({
    session_id: "s1", device_id: "d1", seq, agent: "claude-code",
    kind: "user_message", timestamp: "2026-01-01T00:00:00Z", payload: { text },
  } as SessionTurn);
  const out = reconcileHydratedTurns([mk(17, "first"), mk(19, "second")], [mk(17, "first"), mk(19, "second")])
    .filter((t) => t.kind === "user_message");
  assert.equal(out.length, 2);
});

test("parseUserMessage extracts a slash command name", () => {
  const text = "<command-message>pockly</command-message><command-name>pockly</command-name>";
  const result = parseUserMessage(text);
  assert.equal(result.kind, "slash");
  if (result.kind === "slash") {
    assert.equal(result.command, "pockly");
    assert.equal(result.args, undefined);
  }
});

test("parseUserMessage strips leading slash from command-name", () => {
  const text = "<command-name>/clear</command-name>";
  const result = parseUserMessage(text);
  assert.equal(result.kind, "slash");
  if (result.kind === "slash") {
    assert.equal(result.command, "clear");
  }
});

test("parseUserMessage captures command args and stdout", () => {
  const text =
    "<command-name>/loop</command-name>" +
    "<command-args>5m /babysit-prs</command-args>" +
    "<local-command-stdout>started loop ok</local-command-stdout>";
  const result = parseUserMessage(text);
  assert.equal(result.kind, "slash");
  if (result.kind === "slash") {
    assert.equal(result.command, "loop");
    assert.equal(result.args, "5m /babysit-prs");
    assert.equal(result.output, "started loop ok");
  }
});

test("parseUserMessage demotes Local daemon status to system channel", () => {
  const text = "Local daemon:\nPockly daemon linked · 1 device paired last known\nRemote access: enabled";
  const result = parseUserMessage(text);
  assert.equal(result.kind, "system");
  if (result.kind === "system") {
    assert.ok(result.text.startsWith("Local daemon:"));
  }
});

test("parseUserMessage demotes local-command-stdout-only payloads to system", () => {
  const text = "<local-command-stdout>cleaned 12 files</local-command-stdout>";
  const result = parseUserMessage(text);
  assert.equal(result.kind, "system");
  if (result.kind === "system") {
    assert.equal(result.text, "cleaned 12 files");
  }
});

test("parseUserMessage hides Claude model switch command records", () => {
  const command = "<command-message>/model flash</command-message><command-name>/model</command-name>";
  const commandResult = parseUserMessage(command);
  assert.equal(commandResult.kind, "plain");
  if (commandResult.kind === "plain") {
    assert.equal(commandResult.text, "");
  }

  const stdout = "<local-command-stdout>Set model to anthropic-compatible-fast and saved as your default for new sessions</local-command-stdout>";
  const stdoutResult = parseUserMessage(stdout);
  assert.equal(stdoutResult.kind, "plain");
  if (stdoutResult.kind === "plain") {
    assert.equal(stdoutResult.text, "");
  }
});

test("empty assistant turns are not renderable conversation turns", () => {
  const emptyAssistant: SessionTurn = {
    session_id: "s1",
    device_id: "d1",
    seq: 10,
    agent: "claude-code",
    kind: "assistant_text",
    timestamp: "2026-01-01T00:00:00Z",
    payload: { text: "   " },
  } as SessionTurn;
  assert.equal(isRenderableConversationTurn(emptyAssistant), false);
  assert.deepEqual(visibleConversationTurns([emptyAssistant]), []);
});

test("parseUserMessage falls back to plain when empty after strip", () => {
  const result = parseUserMessage("");
  assert.equal(result.kind, "plain");
});

test("attachmentSummary summarizes skill_listing by counting bullet lines", () => {
  const text = [
    "- pockly: Show daemon status",
    "- update-config: Configure harness",
    "  - nested non-skill line",
    "- review: Review a PR",
  ].join("\n");
  const summary = attachmentSummary("skill_listing", text);
  assert.equal(summary.state, "3");
  assert.ok(summary.label.length > 0);
});

test("attachmentSummary summarizes agent_listing_delta by addedLines count", () => {
  const text = JSON.stringify({ addedLines: ["- claude: cat", "- Explore: search", "- Plan: arch"] });
  const summary = attachmentSummary("agent_listing_delta", text);
  assert.equal(summary.state, "+3");
});

test("attachmentSummary summarizes deferred_tools_delta by addedLines count", () => {
  const text = JSON.stringify({ addedLines: ["CronCreate", "CronDelete", "CronList"] });
  const summary = attachmentSummary("deferred_tools_delta", text);
  assert.equal(summary.state, "+3");
});

test("attachmentSummary surfaces the first allowed tool for command_permissions", () => {
  const text = JSON.stringify({
    allowedTools: ["Bash('/Users/dev/.local/bin/pockly-daemon' claude-status --claude-command)"],
    type: "command_permissions",
  });
  const summary = attachmentSummary("command_permissions", text);
  assert.equal(summary.state, "1");
  assert.equal(summary.preview, "Bash");
});

test("attachmentSummary falls back to the raw type for unknown attachments", () => {
  const summary = attachmentSummary("custom_blob", "");
  assert.equal(summary.state, "custom_blob");
});

test("attachmentSummary tolerates non-JSON delta payloads", () => {
  const summary = attachmentSummary("agent_listing_delta", "free-form text without braces");
  assert.equal(summary.state, "updated");
});

test("visibleConversationTurns hides ALL Claude Code context attachments", () => {
  // Attachments are session-context plumbing, never conversation content, and
  // the type set grows every Claude release — so they're hidden by default.
  // file / nested_memory / invoked_skills / compact_file_reference /
  // edited_text_file / hook_additional_context were leaking as "附件" cards.
  const turns = [
    turn(1, "user_message", { text: "hi" }),
    turn(2, "attachment", { attachment_type: "skill_listing", text: "- Skill" }),
    turn(3, "attachment", { attachment_type: "agent_listing_delta", text: "{\"addedLines\":[\"agent\"]}" }),
    turn(4, "attachment", { attachment_type: "deferred_tools_delta", text: "{\"addedLines\":[\"tool\"]}" }),
    turn(5, "attachment", { attachment_type: "command_permissions", text: "{\"allowedTools\":[\"Bash\"]}" }),
    turn(6, "attachment", { attachment_type: "permission_request", text: "Approve Bash?" }),
    turn(7, "attachment", { attachment_type: "file", text: "notes.md" }),
    turn(8, "attachment", { attachment_type: "nested_memory", text: "MEMORY.md" }),
    turn(9, "attachment", { attachment_type: "invoked_skills", text: "{\"skills\":[]}" }),
    turn(10, "attachment", { attachment_type: "compact_file_reference", text: "a.ts" }),
    turn(11, "attachment", { attachment_type: "edited_text_file", text: "b.ts" }),
    turn(12, "attachment", { attachment_type: "hook_additional_context", text: "ctx" }),
    turn(13, "attachment", { attachment_type: "some_future_context_type", text: "x" }),
    turn(14, "assistant_text", { text: "ready" }),
  ];
  const visible = visibleConversationTurns(turns);
  // Only the real conversation turns survive; every attachment is hidden.
  assert.deepEqual(visible.map((item) => item.seq), [1, 14]);
});

test("visibleConversationTurns hides empty and model-switch user messages", () => {
  const turns = [
    turn(1, "user_message", { text: "switching" }),
    turn(2, "user_message", { text: "" }),
    turn(3, "user_message", { text: "<command-name>/model</command-name>" }),
    turn(4, "user_message", { text: "<local-command-stdout>Set model to anthropic-compatible-fast and saved as your default for new sessions</local-command-stdout>" }),
    turn(5, "assistant_text", { text: "done" }),
  ];

  const visible = visibleConversationTurns(turns);
  assert.deepEqual(visible.map((item) => [item.seq, item.kind, item.payload?.text]), [
    [1, "user_message", "switching"],
    [5, "assistant_text", "done"],
  ]);
});

test("visibleConversationTurns hides empty assistant messages", () => {
  const turns = [
    turn(1, "user_message", { text: "4" }),
    turn(2, "assistant_text", { text: "" }),
    turn(3, "assistant_text", { text: "<antml:thinking>hidden</antml:thinking>" }),
    turn(4, "assistant_text", { text: "Visible answer." }),
  ];

  const visible = visibleConversationTurns(turns);
  assert.deepEqual(visible.map((item) => [item.seq, item.kind, item.payload?.text]), [
    [1, "user_message", "4"],
    [4, "assistant_text", "Visible answer."],
  ]);
});

test("visibleConversationTurns preserves assistant text from Windows Claude PTY history", () => {
  const turns = [
    turn(1, "meta", { text: "session started" }),
    turn(2, "user_message", { text: "6" }),
    turn(3, "attachment", { attachment_type: "skill_listing", text: "- Skill" }),
    turn(4, "thinking", { text: "Need clarify the user's intent." }),
    turn(5, "assistant_text", {
      text: "I see you've sent \"6\", but I don't have enough context to understand what you're referring to. Could you clarify what you'd like me to help with?",
    }),
    turn(6, "meta", { text: "updated" }),
  ];

  const visible = visibleConversationTurns(turns);
  assert.deepEqual(visible.map((item) => [item.seq, item.kind, item.payload?.text]), [
    [2, "user_message", "6"],
    [4, "thinking", "Need clarify the user's intent."],
    [
      5,
      "assistant_text",
      "I see you've sent \"6\", but I don't have enough context to understand what you're referring to. Could you clarify what you'd like me to help with?",
    ],
  ]);
});

test("reconcileHydratedTurns preserves user prompts when a late SDK refresh returns assistant-only rows", () => {
  const current = [
    turn(1, "user_message", { text: "你好" }),
    turn(2, "assistant_text", { text: "你好！有什么可以帮您的吗？" }),
    turn(900_000_001, "user_message", { text: "pwd" }),
  ];
  const hydrated = [
    turn(2, "assistant_text", { text: "你好！有什么可以帮您的吗？" }),
    turn(4, "assistant_text", { text: "当前工作目录是：/home/tester/code/demo" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  assert.deepEqual(reconciled.map((item) => [Math.trunc(item.seq), item.kind, item.payload?.text]), [
    [1, "user_message", "你好"],
    [2, "assistant_text", "你好！有什么可以帮您的吗？"],
    [3, "user_message", "pwd"],
    [4, "assistant_text", "当前工作目录是：/home/tester/code/demo"],
  ]);
  assert.equal(visibleConversationTurns(reconciled).filter((item) => item.kind === "user_message").length, 2);
});

test("reconcileHydratedTurns drops optimistic user duplicate once confirmed", () => {
  const current = [
    turn(1, "user_message", { text: "你好" }),
    turn(900_000_001, "user_message", { text: "pwd" }),
  ];
  const hydrated = [
    turn(1, "user_message", { text: "你好" }),
    turn(3, "user_message", { text: "pwd" }),
    turn(4, "assistant_text", { text: "/home/tester/code/demo" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  assert.deepEqual(reconciled.map((item) => [item.seq, item.kind, item.payload?.text]), [
    [1, "user_message", "你好"],
    [3, "user_message", "pwd"],
    [4, "assistant_text", "/home/tester/code/demo"],
  ]);
});

test("reconcileHydratedTurns drops a live assistant turn once hydrated carries the same reply", () => {
  // Regression: a streamed assistant turn (synthetic seq >= 1e9) and its
  // hydrated counterpart (real seq) both keyed distinctly in mergeTurns,
  // so the reply rendered twice until reload. SDK sessions hit this every
  // turn. After reconcile the reply must appear exactly once.
  const current = [
    turn(1, "user_message", { text: "pwd" }),
    turn(1_000_000_002, "assistant_text", { text: "/Users/dev/code/steward" }),
  ];
  const hydrated = [
    turn(1, "user_message", { text: "pwd" }),
    turn(8, "assistant_text", { text: "/Users/dev/code/steward" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 1, "assistant reply should appear exactly once");
  assert.equal(assistantReplies[0].seq, 8, "the hydrated (real-seq) copy is the survivor");
});

test("reconcileHydratedTurns dedupes a live reply that differs only in internal whitespace", () => {
  // Regression: the streamed copy and the persisted copy can differ by a
  // stray newline / collapsed spaces mid-reply. A plain trim()+equality check
  // missed that and left the reply rendered twice until a reload.
  const current = [
    turn(1, "user_message", { text: "hi" }),
    turn(1_000_000_002, "assistant_text", { text: "你好！\n\n有什么我可以帮你的吗？" }),
  ];
  const hydrated = [
    turn(1, "user_message", { text: "hi" }),
    turn(8, "assistant_text", { text: "你好！ 有什么我可以帮你的吗？" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 1, "whitespace-only difference must still dedupe");
  assert.equal(assistantReplies[0].seq, 8);
});

test("reconcileHydratedTurns dedupes when the live copy ran slightly ahead of the persisted one", () => {
  // The streamed turn occasionally holds a hair more text than the synced
  // copy (a trailing token). Bidirectional containment (length-guarded) still
  // collapses them to one bubble.
  const current = [
    turn(1, "user_message", { text: "hi" }),
    turn(1_000_000_002, "assistant_text", { text: "The deployment finished successfully." }),
  ];
  const hydrated = [
    turn(1, "user_message", { text: "hi" }),
    turn(8, "assistant_text", { text: "The deployment finished" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 1, "live-ahead-of-persisted must still dedupe");
});

test("reconcileHydratedTurns keeps a still-streaming assistant turn the hydration has not caught up to", () => {
  // The live turn must survive while it's genuinely newer than anything
  // hydrated yet — otherwise an in-flight reply would vanish.
  const current = [
    turn(1, "user_message", { text: "hi" }),
    turn(1_000_000_003, "assistant_text", { text: "streaming reply not yet synced" }),
  ];
  const hydrated = [
    turn(1, "user_message", { text: "hi" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 1);
  assert.equal(assistantReplies[0].payload?.text, "streaming reply not yet synced");
});

// ── WS onTurn path: reconcile a single confirmed turn (as the realtime WS
// subscription now does) must drop the optimistic twin. These pin the
// single-confirmed-turn contract that the onTurn fix relies on. ────────────

test("reconcileHydratedTurns drops an optimistic assistant twin when a single confirmed WS turn arrives", () => {
  // Core regression for the WS double-bubble: the live SSE bridge adds an
  // optimistic copy (seq 9e8), and the WS push later delivers the confirmed
  // copy (real seq). After reconcile the reply must appear exactly once and
  // the confirmed (real-seq) copy must survive.
  const current = [
    turn(1, "user_message", { text: "说一句话" }),
    turn(900_000_002, "assistant_text", { text: "好" }),   // optimistic from SSE bridge
  ];
  const hydrated = [
    turn(28, "assistant_text", { text: "好" }),             // single confirmed from WS push
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 1, "WS confirmed turn must supersede the optimistic twin");
  assert.equal(assistantReplies[0].seq, 28, "the confirmed (real-seq) copy is the survivor");
});

test("reconcileHydratedTurns keeps a still-streaming optimistic turn when the single WS turn does not match", () => {
  // Safety check: a confirmed turn that doesn't text-match the optimistic
  // one (e.g. it's an earlier historical turn the subscription re-delivered)
  // must NOT drop the optimistic reply that's still on screen.
  const current = [
    turn(1, "user_message", { text: "hi" }),
    turn(900_000_002, "assistant_text", { text: "still streaming…" }),
  ];
  const hydrated = [
    turn(5, "assistant_text", { text: "an earlier unrelated reply" }),
  ];

  const reconciled = reconcileHydratedTurns(current, hydrated);
  const assistantReplies = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistantReplies.length, 2, "non-matching WS turn must not drop the live streaming reply");
  assert.ok(assistantReplies.some((t) => t.seq === 900_000_002), "optimistic streaming turn must survive");
  assert.ok(assistantReplies.some((t) => t.seq === 5), "confirmed earlier turn must also survive");
});

test("appendStreamingTurn replaces a prior live assistant turn instead of stacking duplicates", () => {
  // While streaming, successive non-append assistant snapshots (synthetic
  // seq >= 1e9) must collapse to ONE live turn, not pile up.
  let turns: SessionTurn[] = [turn(1, "user_message", { text: "q" })];
  turns = appendStreamingTurn(turns, turn(1_000_000_001, "assistant_text", { text: "partial" }));
  turns = appendStreamingTurn(turns, turn(1_000_000_002, "assistant_text", { text: "final complete answer" }));
  const assistants = turns.filter((t) => t.kind === "assistant_text");
  assert.equal(assistants.length, 1);
  assert.equal(assistants[0].payload?.text, "final complete answer");
});

test("appendStreamingTurn accumulates append-deltas onto the live assistant turn", () => {
  let turns: SessionTurn[] = [turn(1, "user_message", { text: "q" })];
  turns = appendStreamingTurn(turns, turn(1_000_000_001, "assistant_text", { text: "Hello " }));
  turns = appendStreamingTurn(turns, turn(1_000_000_001, "assistant_text", { text: "world", append: true }));
  const assistants = turns.filter((t) => t.kind === "assistant_text");
  assert.equal(assistants.length, 1);
  assert.equal(assistants[0].payload?.text, "Hello world");
});

test("daily-flow contract: stream then hydrate shows the reply exactly once", () => {
  // End-to-end (logic layer) regression for the duplicate-reply bug:
  // a live streamed assistant turn (synthetic seq) followed by a catalog
  // hydration carrying the real-seq copy must reconcile to ONE reply.
  // This is the combination appendStreamingTurn + reconcileHydratedTurns
  // that the SDK session render path actually exercises every turn.
  const live = appendStreamingTurn(
    [turn(1, "user_message", { text: "q" })],
    turn(1_000_000_005, "assistant_text", { text: "the answer" }),
  );
  const hydrated = [
    turn(1, "user_message", { text: "q" }),
    turn(2, "assistant_text", { text: "the answer" }),
  ];
  const reconciled = reconcileHydratedTurns(live, hydrated);
  const assistants = reconciled.filter((t) => t.kind === "assistant_text");
  assert.equal(assistants.length, 1, "stream→hydrate must not duplicate the reply");
  assert.equal(assistants[0].seq, 2, "the hydrated real-seq copy survives");
});

test("reconcileHydratedTurns collapses duplicate user-message ghosts to one bubble", () => {
  // Real shape observed live: a follow-up rendered as 5 identical user
  // bubbles — fractional-seq ghosts (11.996/11.997) minted by reconcile's
  // displaySeq slotting + optimistic copies (9e8+) that never got dropped.
  const current = [
    turn(7.999, "user_message", { text: "U1" }),
    turn(11.996, "user_message", { text: "U2" }),
    turn(11.997, "user_message", { text: "U2" }),
    turn(900_000_012, "user_message", { text: "U2" }),
    turn(900_000_015, "user_message", { text: "U2" }),
    turn(12, "assistant_text", { text: "U2" }),
  ];
  const hydrated = [turn(12, "assistant_text", { text: "U2" })];
  const reconciled = reconcileHydratedTurns(current, hydrated);
  const userText = (t: SessionTurn) => (t.payload?.text ?? "").trim();
  assert.equal(reconciled.filter((t) => t.kind === "user_message" && userText(t) === "U2").length, 1);
  assert.equal(reconciled.filter((t) => t.kind === "user_message" && userText(t) === "U1").length, 1);
});

test("reconcileHydratedTurns preserves genuine repeated user messages (distinct integer seqs)", () => {
  // A user really sending the same text twice keeps both bubbles — only
  // optimistic/fractional artifacts are collapsed, not genuine repeats.
  const current = [
    turn(3, "user_message", { text: "hi" }),
    turn(5, "user_message", { text: "hi" }),
  ];
  const hydrated = [
    turn(3, "user_message", { text: "hi" }),
    turn(5, "user_message", { text: "hi" }),
    turn(6, "assistant_text", { text: "ok" }),
  ];
  const reconciled = reconcileHydratedTurns(current, hydrated);
  assert.equal(reconciled.filter((t) => t.kind === "user_message").length, 2);
});

test("liveMessageStableSeqKey keeps tool call, tool result, and assistant segments distinct", () => {
  assert.equal(
    liveMessageStableSeqKey({ role: "tool_call", id: "call_web" }, "2026-05-28T00:00:00Z"),
    "tool_call:call_web",
  );
  assert.equal(
    liveMessageStableSeqKey({ role: "tool_result", id: "call_web" }, "2026-05-28T00:00:01Z"),
    "tool_result:call_web",
  );
  assert.equal(
    liveMessageStableSeqKey({ role: "assistant", uuid: "assistant-1", segment: 1 }),
    "assistant-1:segment:1",
  );
  assert.equal(
    liveMessageStableSeqKey({ role: "assistant", uuid: "assistant-1", segment: 2 }),
    "assistant-1:segment:2",
  );
});

test("stripInternalContent removes system-reminder blocks", () => {
  const text = "Hello\n<system-reminder>noise</system-reminder>\nworld";
  assert.equal(stripInternalContent(text), "Hello\n\nworld");
});

test("stripInternalContent removes antml_thinking artifacts and Request interrupted marker", () => {
  const text = "before\n[Request interrupted by user]\n<antml_thinking>secret</antml_thinking>\nafter";
  assert.equal(stripInternalContent(text), "before\n\nafter");
});

test("stripInternalContent is a no-op for clean prose", () => {
  const text = "Just a normal sentence with < and > characters.";
  assert.equal(stripInternalContent(text), text);
});

test("isCompactSummaryText detects the resume preamble", () => {
  assert.equal(isCompactSummaryText("This session is being continued from a previous conversation."), true);
  assert.equal(isCompactSummaryText("Previous Conversation Compacted\n\nThings happened."), true);
  assert.equal(isCompactSummaryText("Hello, how are you?"), false);
});

test("parseUserMessage classifies a compact-summary preamble as compact", () => {
  const result = parseUserMessage("This session is being continued from a previous conversation.\n\nSummary: …");
  assert.equal(result.kind, "compact");
});

test("isDiffTool matches canonical edit tools only", () => {
  assert.equal(isDiffTool("Edit"), true);
  assert.equal(isDiffTool("MultiEdit"), true);
  assert.equal(isDiffTool("Write"), true);
  assert.equal(isDiffTool("ApplyPatch"), true);
  assert.equal(isDiffTool("Bash"), false);
  assert.equal(isDiffTool("mcp__notion__edit_page"), false);
});

test("extractEditPairs pulls old/new pairs from Edit input", () => {
  const pairs = extractEditPairs("Edit", { file_path: "/a/b.ts", old_string: "foo", new_string: "bar" });
  assert.equal(pairs.length, 1);
  assert.equal(pairs[0].file, "/a/b.ts");
  assert.equal(pairs[0].old, "foo");
  assert.equal(pairs[0].new, "bar");
});

test("extractEditPairs treats Write content as all-add diff", () => {
  const pairs = extractEditPairs("Write", { file_path: "/a/new.ts", content: "line one\nline two" });
  assert.equal(pairs.length, 1);
  assert.equal(pairs[0].old, "");
  assert.equal(pairs[0].new, "line one\nline two");
});

test("extractEditPairs splits MultiEdit edits[]", () => {
  const pairs = extractEditPairs("MultiEdit", {
    file_path: "/a/b.ts",
    edits: [
      { old_string: "a", new_string: "A" },
      { old_string: "b", new_string: "B" },
    ],
  });
  assert.equal(pairs.length, 2);
  assert.equal(pairs[0].new, "A");
  assert.equal(pairs[1].new, "B");
});

test("lineDiff produces a clean diff for a single-line change", () => {
  const ops = lineDiff("alpha\nbeta\ngamma", "alpha\nBETA\ngamma");
  const adds = ops.filter((o) => o.kind === "add").map((o) => o.text);
  const removes = ops.filter((o) => o.kind === "remove").map((o) => o.text);
  assert.deepEqual(adds, ["BETA"]);
  assert.deepEqual(removes, ["beta"]);
});

test("lineDiff classifies pure add when old is empty", () => {
  const ops = lineDiff("", "one\ntwo");
  assert.equal(ops.filter((o) => o.kind === "remove").length, 1); // the implicit empty line
  assert.equal(ops.filter((o) => o.kind === "add").length, 2);
});

test("extractQuestions normalizes AskUserQuestion input", () => {
  const questions = extractQuestions({
    questions: [
      {
        question: "Pick one",
        header: "Auth",
        multiSelect: false,
        options: [
          { label: "OAuth", description: "Use OAuth" },
          { label: "API key" },
        ],
      },
    ],
  });
  assert.equal(questions.length, 1);
  assert.equal(questions[0].question, "Pick one");
  assert.equal(questions[0].header, "Auth");
  assert.equal(questions[0].options.length, 2);
  assert.equal(questions[0].options[1].description, undefined);
});

test("isTodoTool only matches TodoWrite/TodoRead", () => {
  assert.equal(isTodoTool("TodoWrite"), true);
  assert.equal(isTodoTool("todoread"), true);
  assert.equal(isTodoTool("Write"), false);
});

test("extractTodos preserves status and skips empty content", () => {
  const todos = extractTodos({
    todos: [
      { content: "first", status: "completed", activeForm: "Doing first" },
      { content: "", status: "pending" },
      { content: "third" },
    ],
  });
  assert.equal(todos.length, 2);
  assert.equal(todos[0].status, "completed");
  assert.equal(todos[1].status, "unknown");
});

function turn(seq: number, kind: SessionTurn["kind"], payload: NonNullable<SessionTurn["payload"]>): SessionTurn {
  return { session_id: "s", seq, agent: "claude-code", kind, timestamp: "", payload };
}

test("isAgentResponseTurnAfter ignores synced user and thinking turns for first-message completion", () => {
  assert.equal(isAgentResponseTurnAfter(turn(1, "user_message", { text: "prompt" }), 0), false);
  assert.equal(isAgentResponseTurnAfter(turn(2, "thinking", { text: "working" }), 0), false);
  assert.equal(isAgentResponseTurnAfter(turn(3, "assistant_text", { text: "" }), 0), false);
  assert.equal(isAgentResponseTurnAfter(turn(4, "assistant_text", { text: "done" }), 0), true);
  assert.equal(isAgentResponseTurnAfter(turn(5, "tool_call", { tool: "Bash" }), 0), true);
  assert.equal(isAgentResponseTurnAfter(turn(6, "attachment", { attachment_type: "permission_request" }), 0), true);
  assert.equal(isAgentResponseTurnAfter(turn(1_000_000_001, "assistant_text", { text: "optimistic" }), 0), false);
});

test("latestSessionUsage sums input + cache fields from the latest turn carrying usage", () => {
  const turns = [
    turn(1, "assistant_text", { text: "first" }),
    turn(2, "assistant_text", { text: "second", input_tokens: 100, cache_read_input_tokens: 0 }),
    turn(3, "assistant_text", { text: "third", input_tokens: 200, cache_creation_input_tokens: 50, cache_read_input_tokens: 1000 }),
    turn(4, "user_message", { text: "you" }),
  ];
  const usage = latestSessionUsage(turns);
  assert.notEqual(usage, null);
  assert.equal(usage!.used, 1250);
  assert.equal(usage!.total, 200_000);
});

test("latestSessionUsage returns null when no turn carries usage", () => {
  const turns = [turn(1, "assistant_text", { text: "no usage" })];
  assert.equal(latestSessionUsage(turns), null);
});

// Agent-aware context window denominator. Total swaps based on which
// agent recorded the turns. Used count is independent.
test("latestSessionUsage uses Codex context window when agent='codex'", () => {
  const turns = [
    turn(1, "assistant_text", { text: "go", input_tokens: 500 }),
  ];
  const usage = latestSessionUsage(turns, "codex");
  assert.notEqual(usage, null);
  assert.equal(usage!.used, 500);
  assert.equal(usage!.total, 272_000);
});

test("latestSessionUsage defaults to 200k when agent is omitted or unknown", () => {
  const turns = [
    turn(1, "assistant_text", { text: "go", input_tokens: 500 }),
  ];
  assert.equal(latestSessionUsage(turns)!.total, 200_000);
  assert.equal(latestSessionUsage(turns, "mystery-agent")!.total, 200_000);
});

test("contextWindowForAgent picks the right denominator per agent string", () => {
  assert.equal(contextWindowForAgent("claude-code"), 200_000);
  assert.equal(contextWindowForAgent("codex"), 272_000);
  assert.equal(contextWindowForAgent(null), 200_000);
  assert.equal(contextWindowForAgent(undefined), 200_000);
  assert.equal(contextWindowForAgent("unknown-agent"), 200_000);
});

// Pending permission aggregator. Scans turns for unresolved
// permission_request attachments and surfaces a session-wide count.
test("summarizePendingPermissions returns empty on a clean session", () => {
  const turns = [
    turn(1, "assistant_text", { text: "hi" }),
    turn(2, "user_message", { text: "go" }),
  ];
  const sum = summarizePendingPermissions(turns);
  assert.equal(sum.count, 0);
  assert.deepEqual(sum.toolNames, []);
  assert.equal(sum.latestRequestId, "");
});

test("summarizePendingPermissions counts only pending structured requests with request_id", () => {
  const turns = [
    // Pending: counted.
    turn(1, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-1",
      permission_tool_name: "Bash",
      permission_decision: "pending",
    }),
    // Resolved (allow): skipped.
    turn(2, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-2",
      permission_tool_name: "Write",
      permission_decision: "allow",
    }),
    // Older unstructured events without request_id are skipped; their
    // card falls through to the generic renderer.
    turn(3, "tool_result", {
      attachment_type: "permission_request",
      permission_tool_name: "Edit",
    }),
    // Another pending: counted, distinct tool.
    turn(4, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-4",
      permission_tool_name: "Read",
      permission_decision: "pending",
    }),
    // Pending with same tool name as req-1 — counted but deduped in
    // toolNames list.
    turn(5, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-5",
      permission_tool_name: "Bash",
      permission_decision: "pending",
    }),
  ];
  const sum = summarizePendingPermissions(turns);
  assert.equal(sum.count, 3);
  assert.deepEqual(sum.toolNames, ["Bash", "Read"]);
  // Latest by seq, not by array order.
  assert.equal(sum.latestRequestId, "req-5");
});

test("summarizePendingPermissions picks highest seq for latestRequestId regardless of array order", () => {
  const turns = [
    turn(50, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-late",
      permission_tool_name: "Bash",
      permission_decision: "pending",
    }),
    turn(10, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-early",
      permission_tool_name: "Bash",
      permission_decision: "pending",
    }),
  ];
  const sum = summarizePendingPermissions(turns);
  assert.equal(sum.latestRequestId, "req-late");
});

test("summarizePendingPermissions treats missing decision as pending", () => {
  // Some daemon versions omit permission_decision when it would be
  // "pending" by default. The aggregator should treat absence as
  // pending so we don't undercount fresh requests.
  const turns = [
    turn(1, "tool_result", {
      attachment_type: "permission_request",
      permission_request_id: "req-x",
      permission_tool_name: "Bash",
    }),
  ];
  const sum = summarizePendingPermissions(turns);
  assert.equal(sum.count, 1);
  assert.equal(sum.latestRequestId, "req-x");
});

// Reader-preferences parser. Tolerates partial blobs and falls back to
// defaults per key.
test("parseReaderPreferences returns defaults for null / non-object input", () => {
  assert.deepEqual(parseReaderPreferences(null), DEFAULT_READER_PREFERENCES);
  assert.deepEqual(parseReaderPreferences(undefined), DEFAULT_READER_PREFERENCES);
  assert.deepEqual(parseReaderPreferences("not an object"), DEFAULT_READER_PREFERENCES);
  assert.deepEqual(parseReaderPreferences(42), DEFAULT_READER_PREFERENCES);
  assert.deepEqual(parseReaderPreferences([]), DEFAULT_READER_PREFERENCES);
});

test("parseReaderPreferences respects the explicit defaults", () => {
  // New users see: collapsed tool cards, thinking hidden (matches
  // Codex/Claude desktop UX where thinking is a transient state
  // surfaced live via the running indicator, not a persistent
  // transcript item), and raw params visible.
  assert.equal(DEFAULT_READER_PREFERENCES.autoExpandTools, false);
  assert.equal(DEFAULT_READER_PREFERENCES.showThinking, false);
  assert.equal(DEFAULT_READER_PREFERENCES.showRawParameters, true);
});

test("parseReaderPreferences accepts a complete blob round-trip", () => {
  const stored = { autoExpandTools: true, showThinking: false, showRawParameters: false };
  assert.deepEqual(parseReaderPreferences(stored), stored);
});

test("parseReaderPreferences fills missing keys with per-key defaults", () => {
  // Forward-compat: a user upgrading from a build that only persisted
  // autoExpandTools should keep that bit and pick up defaults for the
  // newer toggles.
  const partial = { autoExpandTools: true };
  const merged = parseReaderPreferences(partial);
  assert.equal(merged.autoExpandTools, true);
  assert.equal(merged.showThinking, DEFAULT_READER_PREFERENCES.showThinking);
  assert.equal(merged.showRawParameters, DEFAULT_READER_PREFERENCES.showRawParameters);
});

test("parseReaderPreferences ignores non-boolean values per key", () => {
  // A corrupted entry (string instead of bool, etc.) should not
  // poison the typed snapshot.
  const noisy = {
    autoExpandTools: "yes",
    showThinking: 1,
    showRawParameters: null,
  };
  assert.deepEqual(parseReaderPreferences(noisy), DEFAULT_READER_PREFERENCES);
});

// Math-syntax detector. Drives the lazy-load gate: only when this returns
// true does the markdown pipeline pull in KaTeX.
test("hasMathSyntax returns false on plain text", () => {
  assert.equal(hasMathSyntax(""), false);
  assert.equal(hasMathSyntax("just a sentence with no math"), false);
  assert.equal(hasMathSyntax("backslash but no math \\foo"), false);
});

test("hasMathSyntax detects $$ block delimiters", () => {
  assert.equal(hasMathSyntax("Pythagoras: $$a^2 + b^2 = c^2$$"), true);
  assert.equal(hasMathSyntax("multi-line\n$$\nx = y + z\n$$\nworks"), true);
});

test("hasMathSyntax detects \\[ \\] block delimiters", () => {
  assert.equal(hasMathSyntax("Result: \\[ \\int_0^1 x \\, dx = 1/2 \\]"), true);
});

test("hasMathSyntax detects \\( \\) inline delimiters", () => {
  assert.equal(hasMathSyntax("the slope \\(m\\) is rise over run"), true);
});

test("hasMathSyntax does NOT trip on single-$ currency mentions", () => {
  // Single-$ inline math is intentionally not supported — flag a
  // common false-positive case so a future regex tweak that adds
  // single-$ would fail this test.
  assert.equal(hasMathSyntax("a $5 fix and a $100 upgrade"), false);
  assert.equal(hasMathSyntax("paid $0 — no charge"), false);
});

test("hasMathSyntax ignores math-looking content inside fenced code", () => {
  // Math inside ```...``` should not pull katex in. The markdown
  // renderer's fence tokenizer claims the content before our math
  // extension fires, so we'd just load katex for nothing.
  assert.equal(
    hasMathSyntax("```\nconsole.log('$$nope$$')\n```\nplain text after"),
    false,
  );
  // But math AFTER the fence still triggers.
  assert.equal(
    hasMathSyntax("```\n$$nope$$\n```\nreal: $$x = 1$$"),
    true,
  );
});

test("tokenUsageTier buckets correctly at the 50% / 80% thresholds", () => {
  assert.equal(tokenUsageTier(0), "ok");
  assert.equal(tokenUsageTier(49.9), "ok");
  assert.equal(tokenUsageTier(50), "warn");
  assert.equal(tokenUsageTier(79.9), "warn");
  assert.equal(tokenUsageTier(80), "danger");
  assert.equal(tokenUsageTier(100), "danger");
  // rawPct can exceed 100 before clamping, for example if a Codex session
  // runs beyond the header context window; still danger.
  assert.equal(tokenUsageTier(150), "danger");
});

test("nestSidechainTurns nests sidechain blocks under their Task carrier", () => {
  const turns: SessionTurn[] = [
    turn(1, "user_message", { text: "spawn agent" }),
    turn(2, "tool_call", { tool: "Task", id: "tu_task", input: { description: "search" } }),
    turn(3, "assistant_text", { text: "sub starting", is_sidechain: true, parent_tool_use_id: "tu_task" }),
    turn(4, "tool_call", { tool: "Read", id: "tu_sub_read", input: { file_path: "/x" }, is_sidechain: true, parent_tool_use_id: "tu_task" }),
    turn(5, "tool_result", { id: "tu_task", result: "subagent done", has_result: true }),
  ];
  const nested = nestSidechainTurns(turns);
  // Sidechain turns dropped from main flow; carrier carries them.
  assert.equal(nested.length, 3);
  assert.equal(nested[0].kind, "user_message");
  assert.equal(nested[1].kind, "tool_call");
  assert.equal(nested[1].payload?.tool, "Task");
  assert.equal(nested[1].payload?._sidechain_items?.length, 2);
  assert.equal(nested[2].kind, "tool_result");
});

test("nestSidechainTurns is a no-op when no sidechain turns are present", () => {
  const turns: SessionTurn[] = [
    turn(1, "user_message", { text: "hi" }),
    turn(2, "assistant_text", { text: "hi back" }),
  ];
  const nested = nestSidechainTurns(turns);
  assert.equal(nested, turns);
});

function sessionForControl(overrides: Partial<SessionListItem> = {}): SessionListItem {
  return {
    session_id: "sess",
    device_id: "daemon",
    agent: "claude-code",
    cwd: "/repo",
    snippet: "demo",
    last_seq: 1,
    last_timestamp: "2026-05-25T00:00:00Z",
    ...overrides,
  };
}

test("canControlSession allows any writable session regardless of driver", () => {
  // Dual-driver model: writability is the gate, not a specific
  // connection_mode. PTY mirror and SDK headless are both writable when
  // daemon is online; Nexus surfaces that via the `writable` field.
  assert.equal(canControlSession(sessionForControl({ connection_mode: "pty_backed_duplex", writable: true })), true);
  assert.equal(canControlSession(sessionForControl({ connection_mode: "sdk_headless", writable: true })), true);
  assert.equal(canControlSession(sessionForControl({ connection_mode: "sdk_running", writable: true })), true);
  assert.equal(canControlSession(sessionForControl({ connection_mode: "pty_backed_duplex", writable: false })), false);
  assert.equal(canControlSession(sessionForControl({ connection_mode: "read_only", writable: false })), false);
  // Legacy values from older Nexus builds decay through sessionConnectionMode
  // but `writable` is still authoritative for control:
  assert.equal(canControlSession(sessionForControl({ connection_mode: "detached", writable: false })), false);
  assert.equal(canControlSession(sessionForControl({ connection_mode: "read_only_sync", writable: false })), false);
  assert.equal(canControlSession(null), false);
});

test("canControlSession treats draft conversations as controllable", () => {
  // Drafts are client-only until the user sends the first message — they
  // never have writable=true, but the composer must stay enabled so the
  // send action can promote the draft into a real daemon session.
  const draft = {
    ...sessionForControl({ writable: false }),
    isDraft: true as const,
    session_id: `draft_${Date.now().toString(36)}_abcdef`,
  };
  assert.equal(canControlSession(draft), true);
});
